name: ht_categories_repository
description: A Dart package providing a repository implementation for managing news categories.
repository: https://github.com/headlines-toolkit/ht-categories-repository
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  ht_categories_client:
    git:
      url: https://github.com/headlines-toolkit/ht-categories-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
            
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
